title: Emmanuel Bernard

profiles:
  development:
    disqus_developer: true
    dev: true
  staging:
    base_url: http://test.emmanuelbernard.com/
    deploy:
      host: emmanue2@emmanuelbernard.com
      path: /home1/emmanue2/public_html/test
  production:
    base_url: http://emmanuelbernard.com/
    deploy:
      host: emmanue2@emmanuelbernard.com
      path: /home1/emmanue2/public_html/test

google_analytics: UA-3479508-6
flattr_username: epbernard
disqus: emmanuelbernard-com