title: Emmanuel Bernard

profiles:
  development:
    disqus_developer: true
    dev: true
  production:
    base_url: http://emmanuelbernard.com/

google_analytics: UA-3479508-6
flattr_username: epbernard
disqus: emmanuelbernard-com